# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'DataProcessingConfigurationForm.ui'
#
# Created by: PyQt5 UI code generator 5.12.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_dataProcessingConfigurationForm(object):
    def setupUi(self, dataProcessingConfigurationForm):
        dataProcessingConfigurationForm.setObjectName("dataProcessingConfigurationForm")
        dataProcessingConfigurationForm.resize(464, 430)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(dataProcessingConfigurationForm.sizePolicy().hasHeightForWidth())
        dataProcessingConfigurationForm.setSizePolicy(sizePolicy)
        self.label = QtWidgets.QLabel(dataProcessingConfigurationForm)
        self.label.setGeometry(QtCore.QRect(60, 20, 321, 51))
        font = QtGui.QFont()
        font.setFamily("Open Sans")
        font.setPointSize(16)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(dataProcessingConfigurationForm)
        self.label_2.setGeometry(QtCore.QRect(40, 110, 71, 41))
        font = QtGui.QFont()
        font.setFamily("Open Sans")
        font.setPointSize(11)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(dataProcessingConfigurationForm)
        self.label_3.setGeometry(QtCore.QRect(300, 90, 151, 21))
        font = QtGui.QFont()
        font.setFamily("Open Sans")
        font.setPointSize(10)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.waveletStrLineEd = QtWidgets.QLineEdit(dataProcessingConfigurationForm)
        self.waveletStrLineEd.setGeometry(QtCore.QRect(110, 120, 141, 20))
        self.waveletStrLineEd.setObjectName("waveletStrLineEd")
        self.decomposeLvlSpinBox = QtWidgets.QSpinBox(dataProcessingConfigurationForm)
        self.decomposeLvlSpinBox.setGeometry(QtCore.QRect(340, 120, 42, 22))
        self.decomposeLvlSpinBox.setObjectName("decomposeLvlSpinBox")
        self.label_4 = QtWidgets.QLabel(dataProcessingConfigurationForm)
        self.label_4.setGeometry(QtCore.QRect(40, 160, 131, 41))
        font = QtGui.QFont()
        font.setFamily("Open Sans")
        font.setPointSize(11)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(dataProcessingConfigurationForm)
        self.label_5.setGeometry(QtCore.QRect(50, 200, 71, 16))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(dataProcessingConfigurationForm)
        self.label_6.setGeometry(QtCore.QRect(50, 220, 71, 16))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(dataProcessingConfigurationForm)
        self.label_7.setGeometry(QtCore.QRect(50, 240, 91, 16))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(dataProcessingConfigurationForm)
        self.label_8.setGeometry(QtCore.QRect(50, 260, 91, 16))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.label_9 = QtWidgets.QLabel(dataProcessingConfigurationForm)
        self.label_9.setGeometry(QtCore.QRect(50, 280, 51, 16))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        self.label_9.setFont(font)
        self.label_9.setObjectName("label_9")
        self.label_10 = QtWidgets.QLabel(dataProcessingConfigurationForm)
        self.label_10.setGeometry(QtCore.QRect(120, 280, 51, 16))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        self.label_10.setFont(font)
        self.label_10.setObjectName("label_10")
        self.label_11 = QtWidgets.QLabel(dataProcessingConfigurationForm)
        self.label_11.setGeometry(QtCore.QRect(180, 280, 51, 16))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        self.label_11.setFont(font)
        self.label_11.setObjectName("label_11")
        self.label_12 = QtWidgets.QLabel(dataProcessingConfigurationForm)
        self.label_12.setGeometry(QtCore.QRect(50, 300, 51, 16))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        self.label_12.setFont(font)
        self.label_12.setObjectName("label_12")
        self.label_13 = QtWidgets.QLabel(dataProcessingConfigurationForm)
        self.label_13.setGeometry(QtCore.QRect(120, 300, 51, 16))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        self.label_13.setFont(font)
        self.label_13.setObjectName("label_13")
        self.label_14 = QtWidgets.QLabel(dataProcessingConfigurationForm)
        self.label_14.setGeometry(QtCore.QRect(180, 300, 51, 16))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        self.label_14.setFont(font)
        self.label_14.setObjectName("label_14")
        self.label_15 = QtWidgets.QLabel(dataProcessingConfigurationForm)
        self.label_15.setGeometry(QtCore.QRect(240, 300, 51, 16))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        self.label_15.setFont(font)
        self.label_15.setObjectName("label_15")
        self.label_16 = QtWidgets.QLabel(dataProcessingConfigurationForm)
        self.label_16.setGeometry(QtCore.QRect(120, 320, 51, 16))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        self.label_16.setFont(font)
        self.label_16.setObjectName("label_16")
        self.label_17 = QtWidgets.QLabel(dataProcessingConfigurationForm)
        self.label_17.setGeometry(QtCore.QRect(180, 320, 51, 16))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        self.label_17.setFont(font)
        self.label_17.setObjectName("label_17")
        self.label_18 = QtWidgets.QLabel(dataProcessingConfigurationForm)
        self.label_18.setGeometry(QtCore.QRect(240, 320, 51, 16))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        self.label_18.setFont(font)
        self.label_18.setObjectName("label_18")
        self.label_19 = QtWidgets.QLabel(dataProcessingConfigurationForm)
        self.label_19.setGeometry(QtCore.QRect(50, 320, 51, 16))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        self.label_19.setFont(font)
        self.label_19.setObjectName("label_19")
        self.label_20 = QtWidgets.QLabel(dataProcessingConfigurationForm)
        self.label_20.setGeometry(QtCore.QRect(300, 320, 51, 16))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        self.label_20.setFont(font)
        self.label_20.setObjectName("label_20")
        self.label_21 = QtWidgets.QLabel(dataProcessingConfigurationForm)
        self.label_21.setGeometry(QtCore.QRect(180, 340, 51, 16))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        self.label_21.setFont(font)
        self.label_21.setObjectName("label_21")
        self.label_22 = QtWidgets.QLabel(dataProcessingConfigurationForm)
        self.label_22.setGeometry(QtCore.QRect(120, 340, 51, 16))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        self.label_22.setFont(font)
        self.label_22.setObjectName("label_22")
        self.label_23 = QtWidgets.QLabel(dataProcessingConfigurationForm)
        self.label_23.setGeometry(QtCore.QRect(50, 340, 51, 16))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        self.label_23.setFont(font)
        self.label_23.setObjectName("label_23")
        self.pushButton = QtWidgets.QPushButton(dataProcessingConfigurationForm)
        self.pushButton.setGeometry(QtCore.QRect(190, 380, 91, 31))
        self.pushButton.setObjectName("pushButton")

        self.retranslateUi(dataProcessingConfigurationForm)
        QtCore.QMetaObject.connectSlotsByName(dataProcessingConfigurationForm)

    def retranslateUi(self, dataProcessingConfigurationForm):
        _translate = QtCore.QCoreApplication.translate
        dataProcessingConfigurationForm.setWindowTitle(_translate("dataProcessingConfigurationForm", "Form"))
        self.label.setText(_translate("dataProcessingConfigurationForm", "Wavelet Denoising Configuration"))
        self.label_2.setText(_translate("dataProcessingConfigurationForm", "Wavelet:"))
        self.label_3.setText(_translate("dataProcessingConfigurationForm", "Decomposition Level:"))
        self.label_4.setText(_translate("dataProcessingConfigurationForm", "Supported values:"))
        self.label_5.setText(_translate("dataProcessingConfigurationForm", "db1 .. db15"))
        self.label_6.setText(_translate("dataProcessingConfigurationForm", "haar"))
        self.label_7.setText(_translate("dataProcessingConfigurationForm", "sym2 .. sym10"))
        self.label_8.setText(_translate("dataProcessingConfigurationForm", "coif1 .. coif5"))
        self.label_9.setText(_translate("dataProcessingConfigurationForm", "bior1.1"))
        self.label_10.setText(_translate("dataProcessingConfigurationForm", "bior1.3"))
        self.label_11.setText(_translate("dataProcessingConfigurationForm", "bior1.5"))
        self.label_12.setText(_translate("dataProcessingConfigurationForm", "bior2.2"))
        self.label_13.setText(_translate("dataProcessingConfigurationForm", "bior2.4"))
        self.label_14.setText(_translate("dataProcessingConfigurationForm", "bior2.6"))
        self.label_15.setText(_translate("dataProcessingConfigurationForm", "bior2.8"))
        self.label_16.setText(_translate("dataProcessingConfigurationForm", "bior3.3"))
        self.label_17.setText(_translate("dataProcessingConfigurationForm", "bior3.5"))
        self.label_18.setText(_translate("dataProcessingConfigurationForm", "bior3.7"))
        self.label_19.setText(_translate("dataProcessingConfigurationForm", "bior3.1"))
        self.label_20.setText(_translate("dataProcessingConfigurationForm", "bior3.9"))
        self.label_21.setText(_translate("dataProcessingConfigurationForm", "bior6.8"))
        self.label_22.setText(_translate("dataProcessingConfigurationForm", "bior5.5"))
        self.label_23.setText(_translate("dataProcessingConfigurationForm", "bior4.4"))
        self.pushButton.setText(_translate("dataProcessingConfigurationForm", "Apply"))




if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    dataProcessingConfigurationForm = QtWidgets.QWidget()
    ui = Ui_dataProcessingConfigurationForm()
    ui.setupUi(dataProcessingConfigurationForm)
    dataProcessingConfigurationForm.show()
    sys.exit(app.exec_())
