# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'DMCModForm.ui'
#
# Created by: PyQt5 UI code generator 5.12.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_DmcEegModForm(object):
    def setupUi(self, DmcEegModForm):
        DmcEegModForm.setObjectName("DmcEegModForm")
        DmcEegModForm.resize(492, 666)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(DmcEegModForm.sizePolicy().hasHeightForWidth())
        DmcEegModForm.setSizePolicy(sizePolicy)
        DmcEegModForm.setMinimumSize(QtCore.QSize(492, 633))
        self.label = QtWidgets.QLabel(DmcEegModForm)
        self.label.setGeometry(QtCore.QRect(90, 40, 291, 16))
        font = QtGui.QFont()
        font.setFamily("Open Sans")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.connectBtn = QtWidgets.QPushButton(DmcEegModForm)
        self.connectBtn.setGeometry(QtCore.QRect(50, 100, 91, 41))
        font = QtGui.QFont()
        font.setFamily("Open Sans")
        font.setPointSize(10)
        self.connectBtn.setFont(font)
        self.connectBtn.setObjectName("connectBtn")
        self.label_2 = QtWidgets.QLabel(DmcEegModForm)
        self.label_2.setGeometry(QtCore.QRect(210, 100, 61, 41))
        font = QtGui.QFont()
        font.setFamily("Open Sans")
        font.setPointSize(10)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.setValBtn = QtWidgets.QPushButton(DmcEegModForm)
        self.setValBtn.setGeometry(QtCore.QRect(350, 110, 75, 23))
        font = QtGui.QFont()
        font.setFamily("Open Sans")
        self.setValBtn.setFont(font)
        self.setValBtn.setObjectName("setValBtn")
        self.valSpinBox = QtWidgets.QSpinBox(DmcEegModForm)
        self.valSpinBox.setGeometry(QtCore.QRect(290, 110, 42, 22))
        font = QtGui.QFont()
        font.setFamily("Open Sans")
        self.valSpinBox.setFont(font)
        self.valSpinBox.setMaximum(300)
        self.valSpinBox.setObjectName("valSpinBox")
        self.label_3 = QtWidgets.QLabel(DmcEegModForm)
        self.label_3.setGeometry(QtCore.QRect(20, 250, 181, 16))
        font = QtGui.QFont()
        font.setFamily("Open Sans")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(DmcEegModForm)
        self.label_4.setGeometry(QtCore.QRect(50, 160, 161, 21))
        font = QtGui.QFont()
        font.setFamily("Open Sans")
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.valUpdateIntervalSpinBox = QtWidgets.QSpinBox(DmcEegModForm)
        self.valUpdateIntervalSpinBox.setGeometry(QtCore.QRect(220, 160, 42, 22))
        self.valUpdateIntervalSpinBox.setMinimum(1)
        self.valUpdateIntervalSpinBox.setMaximum(1000)
        self.valUpdateIntervalSpinBox.setObjectName("valUpdateIntervalSpinBox")
        self.label_5 = QtWidgets.QLabel(DmcEegModForm)
        self.label_5.setGeometry(QtCore.QRect(270, 160, 31, 21))
        font = QtGui.QFont()
        font.setFamily("Open Sans")
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.label_7 = QtWidgets.QLabel(DmcEegModForm)
        self.label_7.setGeometry(QtCore.QRect(40, 280, 101, 21))
        font = QtGui.QFont()
        font.setFamily("Open Sans")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.label_9 = QtWidgets.QLabel(DmcEegModForm)
        self.label_9.setGeometry(QtCore.QRect(40, 320, 131, 21))
        font = QtGui.QFont()
        font.setFamily("Open Sans")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.label_9.setFont(font)
        self.label_9.setObjectName("label_9")
        self.label_11 = QtWidgets.QLabel(DmcEegModForm)
        self.label_11.setGeometry(QtCore.QRect(40, 360, 131, 21))
        font = QtGui.QFont()
        font.setFamily("Open Sans")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.label_11.setFont(font)
        self.label_11.setObjectName("label_11")
        self.thrSpinBox = QtWidgets.QDoubleSpinBox(DmcEegModForm)
        self.thrSpinBox.setGeometry(QtCore.QRect(190, 280, 62, 22))
        self.thrSpinBox.setMaximum(1.0)
        self.thrSpinBox.setSingleStep(0.1)
        self.thrSpinBox.setProperty("value", 0.5)
        self.thrSpinBox.setObjectName("thrSpinBox")
        self.subSpinBox = QtWidgets.QDoubleSpinBox(DmcEegModForm)
        self.subSpinBox.setGeometry(QtCore.QRect(190, 320, 62, 22))
        self.subSpinBox.setMaximum(100.0)
        self.subSpinBox.setSingleStep(0.5)
        self.subSpinBox.setProperty("value", 1.0)
        self.subSpinBox.setObjectName("subSpinBox")
        self.addSpinBox = QtWidgets.QDoubleSpinBox(DmcEegModForm)
        self.addSpinBox.setGeometry(QtCore.QRect(190, 360, 62, 22))
        self.addSpinBox.setSingleStep(0.5)
        self.addSpinBox.setProperty("value", 1.0)
        self.addSpinBox.setObjectName("addSpinBox")
        self.label_12 = QtWidgets.QLabel(DmcEegModForm)
        self.label_12.setGeometry(QtCore.QRect(40, 460, 151, 21))
        font = QtGui.QFont()
        font.setFamily("Open Sans")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.label_12.setFont(font)
        self.label_12.setObjectName("label_12")
        self.label_13 = QtWidgets.QLabel(DmcEegModForm)
        self.label_13.setGeometry(QtCore.QRect(40, 520, 151, 21))
        font = QtGui.QFont()
        font.setFamily("Open Sans")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.label_13.setFont(font)
        self.label_13.setObjectName("label_13")
        self.label_14 = QtWidgets.QLabel(DmcEegModForm)
        self.label_14.setGeometry(QtCore.QRect(40, 580, 81, 21))
        font = QtGui.QFont()
        font.setFamily("Open Sans")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.label_14.setFont(font)
        self.label_14.setObjectName("label_14")
        self.label_6 = QtWidgets.QLabel(DmcEegModForm)
        self.label_6.setGeometry(QtCore.QRect(20, 430, 71, 16))
        font = QtGui.QFont()
        font.setFamily("Open Sans")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.incombatCheckBox = QtWidgets.QCheckBox(DmcEegModForm)
        self.incombatCheckBox.setGeometry(QtCore.QRect(130, 580, 21, 21))
        self.incombatCheckBox.setText("")
        self.incombatCheckBox.setCheckable(False)
        self.incombatCheckBox.setObjectName("incombatCheckBox")
        self.concentrationLabel = QtWidgets.QLabel(DmcEegModForm)
        self.concentrationLabel.setGeometry(QtCore.QRect(200, 460, 61, 21))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.concentrationLabel.setFont(font)
        self.concentrationLabel.setObjectName("concentrationLabel")
        self.gameLabel = QtWidgets.QLabel(DmcEegModForm)
        self.gameLabel.setGeometry(QtCore.QRect(200, 520, 61, 21))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.gameLabel.setFont(font)
        self.gameLabel.setObjectName("gameLabel")
        self.startBtn = QtWidgets.QPushButton(DmcEegModForm)
        self.startBtn.setGeometry(QtCore.QRect(200, 610, 101, 41))
        font = QtGui.QFont()
        font.setFamily("Open Sans")
        font.setPointSize(10)
        self.startBtn.setFont(font)
        self.startBtn.setObjectName("startBtn")
        self.label_15 = QtWidgets.QLabel(DmcEegModForm)
        self.label_15.setGeometry(QtCore.QRect(40, 490, 151, 21))
        font = QtGui.QFont()
        font.setFamily("Open Sans")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.label_15.setFont(font)
        self.label_15.setObjectName("label_15")
        self.updateLabel = QtWidgets.QLabel(DmcEegModForm)
        self.updateLabel.setGeometry(QtCore.QRect(200, 490, 61, 21))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.updateLabel.setFont(font)
        self.updateLabel.setObjectName("updateLabel")
        self.injectIntervalSpinBox = QtWidgets.QSpinBox(DmcEegModForm)
        self.injectIntervalSpinBox.setGeometry(QtCore.QRect(220, 200, 42, 22))
        self.injectIntervalSpinBox.setMinimum(1)
        self.injectIntervalSpinBox.setMaximum(1000)
        self.injectIntervalSpinBox.setObjectName("injectIntervalSpinBox")
        self.label_8 = QtWidgets.QLabel(DmcEegModForm)
        self.label_8.setGeometry(QtCore.QRect(270, 200, 31, 21))
        font = QtGui.QFont()
        font.setFamily("Open Sans")
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.label_10 = QtWidgets.QLabel(DmcEegModForm)
        self.label_10.setGeometry(QtCore.QRect(50, 200, 131, 21))
        font = QtGui.QFont()
        font.setFamily("Open Sans")
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        self.label_10.setFont(font)
        self.label_10.setObjectName("label_10")
        self.nextGameLabel = QtWidgets.QLabel(DmcEegModForm)
        self.nextGameLabel.setGeometry(QtCore.QRect(200, 550, 61, 21))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.nextGameLabel.setFont(font)
        self.nextGameLabel.setObjectName("nextGameLabel")
        self.label_16 = QtWidgets.QLabel(DmcEegModForm)
        self.label_16.setGeometry(QtCore.QRect(40, 550, 151, 21))
        font = QtGui.QFont()
        font.setFamily("Open Sans")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.label_16.setFont(font)
        self.label_16.setObjectName("label_16")

        self.retranslateUi(DmcEegModForm)
        QtCore.QMetaObject.connectSlotsByName(DmcEegModForm)

    def retranslateUi(self, DmcEegModForm):
        _translate = QtCore.QCoreApplication.translate
        DmcEegModForm.setWindowTitle(_translate("DmcEegModForm", "Form"))
        self.label.setText(_translate("DmcEegModForm", "DMC5 EEG Concentration Mod"))
        self.connectBtn.setText(_translate("DmcEegModForm", "Connect"))
        self.label_2.setText(_translate("DmcEegModForm", "Set Value:"))
        self.setValBtn.setText(_translate("DmcEegModForm", "Set"))
        self.label_3.setText(_translate("DmcEegModForm", "Update Parameters:"))
        self.label_4.setText(_translate("DmcEegModForm", "Value Update Interval:"))
        self.label_5.setText(_translate("DmcEegModForm", "msc"))
        self.label_7.setText(_translate("DmcEegModForm", "Boundry Thr:"))
        self.label_9.setText(_translate("DmcEegModForm", "Subtract Multiplayer:"))
        self.label_11.setText(_translate("DmcEegModForm", "Addition Multiplayer:"))
        self.label_12.setText(_translate("DmcEegModForm", "Current Concentration:"))
        self.label_13.setText(_translate("DmcEegModForm", "Current Game Value:"))
        self.label_14.setText(_translate("DmcEegModForm", "In Combat:"))
        self.label_6.setText(_translate("DmcEegModForm", "Status:"))
        self.concentrationLabel.setText(_translate("DmcEegModForm", "0"))
        self.gameLabel.setText(_translate("DmcEegModForm", "0"))
        self.startBtn.setText(_translate("DmcEegModForm", "Start Injection"))
        self.label_15.setText(_translate("DmcEegModForm", "Current Update Value:"))
        self.updateLabel.setText(_translate("DmcEegModForm", "0"))
        self.label_8.setText(_translate("DmcEegModForm", "msc"))
        self.label_10.setText(_translate("DmcEegModForm", "Injection Interval:"))
        self.nextGameLabel.setText(_translate("DmcEegModForm", "0"))
        self.label_16.setText(_translate("DmcEegModForm", "Next Game Value:"))




if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    DmcEegModForm = QtWidgets.QWidget()
    ui = Ui_DmcEegModForm()
    ui.setupUi(DmcEegModForm)
    DmcEegModForm.show()
    sys.exit(app.exec_())
