# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'SerialConnectionForm.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_serialConnectionForm(object):
    def setupUi(self, serialConnectionForm):
        serialConnectionForm.setObjectName("serialConnectionForm")
        serialConnectionForm.resize(390, 500)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(serialConnectionForm.sizePolicy().hasHeightForWidth())
        serialConnectionForm.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(16)
        serialConnectionForm.setFont(font)
        serialConnectionForm.setStyleSheet("")
        self.startButton = QtWidgets.QPushButton(serialConnectionForm)
        self.startButton.setGeometry(QtCore.QRect(140, 390, 111, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.startButton.setFont(font)
        self.startButton.setStyleSheet("QPushButton {\n"
"    color: #333;\n"
"    border: 2px solid #555;\n"
"    border-radius: 20px;\n"
"    border-style: outset;\n"
"    background: qradialgradient(\n"
"        cx: 0.3, cy: -0.4, fx: 0.3, fy: -0.4,\n"
"        radius: 1.35, stop: 0 #fff, stop: 1 #888\n"
"        );\n"
"    padding: 5px;\n"
"    }\n"
"\n"
"QPushButton:hover {\n"
"    background: qradialgradient(\n"
"        cx: 0.3, cy: -0.4, fx: 0.3, fy: -0.4,\n"
"        radius: 1.35, stop: 0 #fff, stop: 1 #bbb\n"
"        );\n"
"    }\n"
"\n"
"QPushButton:pressed {\n"
"    border-style: inset;\n"
"    background: qradialgradient(\n"
"        cx: 0.4, cy: -0.1, fx: 0.4, fy: -0.1,\n"
"        radius: 1.35, stop: 0 #fff, stop: 1 #ddd\n"
"        );\n"
"    }")
        self.startButton.setObjectName("startButton")
        self.frame = QtWidgets.QFrame(serialConnectionForm)
        self.frame.setGeometry(QtCore.QRect(10, 110, 371, 161))
        self.frame.setStyleSheet("background-color: rgb(247, 247, 247);")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.serialPortInput = QtWidgets.QLineEdit(self.frame)
        self.serialPortInput.setGeometry(QtCore.QRect(190, 30, 171, 20))
        self.serialPortInput.setObjectName("serialPortInput")
        self.portLabel = QtWidgets.QLabel(self.frame)
        self.portLabel.setGeometry(QtCore.QRect(20, 30, 151, 16))
        font = QtGui.QFont()
        font.setFamily("Open Sans")
        font.setPointSize(12)
        self.portLabel.setFont(font)
        self.portLabel.setObjectName("portLabel")
        self.idLabel = QtWidgets.QLabel(self.frame)
        self.idLabel.setGeometry(QtCore.QRect(20, 100, 161, 16))
        font = QtGui.QFont()
        font.setFamily("Open Sans")
        font.setPointSize(12)
        self.idLabel.setFont(font)
        self.idLabel.setObjectName("idLabel")
        self.idInput = QtWidgets.QSpinBox(self.frame)
        self.idInput.setGeometry(QtCore.QRect(190, 100, 42, 22))
        self.idInput.setObjectName("idInput")
        self.headLabel = QtWidgets.QLabel(serialConnectionForm)
        self.headLabel.setGeometry(QtCore.QRect(80, 30, 231, 31))
        font = QtGui.QFont()
        font.setFamily("Open Sans")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.headLabel.setFont(font)
        self.headLabel.setStyleSheet("color: rgb(255, 255, 255);\n"
"background: none;")
        self.headLabel.setObjectName("headLabel")
        self.frame_2 = QtWidgets.QFrame(serialConnectionForm)
        self.frame_2.setGeometry(QtCore.QRect(-10, 0, 411, 501))
        self.frame_2.setStyleSheet("background-color: qlineargradient(spread:reflect, x1:0, y1:0, x2:0.551, y2:0.517, stop:0 rgba(0, 0, 0, 255), stop:0.545455 rgba(74, 74, 74, 255), stop:0.880682 rgba(54, 54, 54, 255));")
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.frame_2.raise_()
        self.frame.raise_()
        self.startButton.raise_()
        self.headLabel.raise_()

        self.retranslateUi(serialConnectionForm)
        QtCore.QMetaObject.connectSlotsByName(serialConnectionForm)

    def retranslateUi(self, serialConnectionForm):
        _translate = QtCore.QCoreApplication.translate
        serialConnectionForm.setWindowTitle(_translate("serialConnectionForm", "Serial Connection"))
        self.startButton.setText(_translate("serialConnectionForm", "Start Stream"))
        self.portLabel.setText(_translate("serialConnectionForm", "Serial Port:"))
        self.idLabel.setText(_translate("serialConnectionForm", "BrainFlow Board ID:"))
        self.headLabel.setText(_translate("serialConnectionForm", "Serial Board Connection"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    serialConnectionForm = QtWidgets.QWidget()
    ui = Ui_serialConnectionForm()
    ui.setupUi(serialConnectionForm)
    serialConnectionForm.show()
    sys.exit(app.exec_())
